baseurl = "https://aarynsmith.com/"
DefaultContentLanguage = "en"
title = "Aaryn Smith"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsCodeFences = true
pygmentsUseClasses = true
disqusShortname = "aarynsmith-com"


[Params]
  subtitle = "Developer / Sysadmin / Jack of all trades"
  logo = "img/Gopher-BG.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = false
  readingTime = true
  socialShare = false
  quantcast = "p-4fB4sM_5pRWvK"

[Author]
  name = "Aaryn Smith"
  website = "https://aarynsmith.com/"
  email = "aarynsmith<AT>gmail<DOT>com"
  github = "AarynSmith"
  gitlab = "aarynsmith"

[[menu.main]]
    name = "Resume"
    url = "https://aarynsmith.gitlab.io/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "pages/about-me/"
    weight = 10

[[menu.main]]
    name = "Blog"
    url = "blog/"
    weight = 20

[[menu.main]]
    name = "Projects"
    url = "projects/"
    weight = 30
