baseurl = "https://aarynsmith.gitlab.io/"
DefaultContentLanguage = "en"
title = "Aaryn Smith"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#disqusShortname = "aarynsmith-github-io"
googleAnalytics = "UA-117169357-1"

[Params]
  subtitle = "Developer / Sysadmin / Jack of all trades"
#   logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = false
  readingTime = true
  useHLJS = true
  socialShare = false

[Author]
  name = "Aaryn Smith"
  website = "aarynsmith.github.io"
  email = "aarynsmith<AT>gmail<DOT>com"
  github = "AarynSmith"
  gitlab = "aarynsmith"
  linkedin = "aaryn-smith"
  stackoverflow = "users/9608512/aaryn-smith"

[[menu.main]]
    name = "Blog"
    url = "blog/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "pages/about-me/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "projects/"
    weight = 3
